file <- read.table("household_power_consumption.txt",sep=";",header=T)
subdata<-subset(file,file$Date=="1/2/2007"|file$Date=="2/2/2007")
####Plot3####
png("plot3.png")
subdata$Date<-as.Date(subdata$Date,format = "%d/%m/%Y")
subdata$Time<-strptime(subdata$Time,format = "%H:%M:%S")
a<-subdata$Date=="2007-02-01"
sum(a)
subdata[1:1440,"Time"] <- format(subdata[1:1440,"Time"],"2007-02-01 %H:%M:%S")
subdata[1441:2880,"Time"] <- format(subdata[1441:2880,"Time"],"2007-02-02 %H:%M:%S")
plot(subdata$Time,subdata$Sub_metering_1,type="n",xlab="",ylab="Energy sub metering")
with(subdata,lines(Time,as.numeric(Sub_metering_1)))
with(subdata,lines(Time,as.numeric(Sub_metering_2),col="red"))
with(subdata,lines(Time,as.numeric(Sub_metering_3),col="blue"))
legend("topright",col=c("black","red","blue"),lty=1,legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
title(main="Energy sub-metering")
dev.off()
